### ISSUE TITLE
README.md dosyasına English versiyonunu link ile ekleyin.

### ISSUE THREAD

**Issue by dkarakay** [CodeKal/About-CodeKAL#28]
README.md dosyasına English versiyonunu link ile ekleyin. Yani README.md içerisine "English" adıyla README_en.md dosyasını açacak şekilde link ekleyin. 

İpucu: https://github.com/blog/1395-relative-links-in-markup-files

**Comment by vaibhavdaren** [comment]
may i work on it?

**Comment by dkarakay** [comment]
Yes, sure

**Comment by vaibhavdaren** [comment]
@dkarakay  done :+1:
